version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3434:3434"
    volumes:
      - .env:/app/
    # environment:      
    #   - API_KEY=bbbb
    env_file:
      - .env
    networks:
      - webnet

  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3005:80"  
    networks:
      - webnet
    depends_on:
      - backend

networks:
  webnet:
