version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3434:3434"
    networks:
      - webnet
  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:80"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "3004:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - backend
      - frontend
    networks:
      - webnet

networks:
  webnet:
