version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # ports:
    #   - "3434:3434"
    networks:
      - webnet
  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3005:80"  
    networks:
      - webnet
    depends_on:
      - backend

networks:
  webnet:
